# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

In [ ]:
np

## Creating arrays


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  5,  7, 12])

In [12]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [14]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [16]:
n[0, 1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [34]:
n[2] = [1, 1, 1]

In [ ]:
n

In [18]:
n[:, 2] = [0, 1, 2]

In [19]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 7,  8,  2]])

## Randomly generated arrays


In [ ]:
np.random.seed(2)
100 * np.random.rand(5, 2)

In [ ]:
np.random.seed(2)
np.random.randn(5, 2)

In [ ]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

## Element-wise operations


In [20]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
b = (10 + (a * 2)) ** 2 / 100

In [22]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [23]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [ ]:
a

In [ ]:
a >= 2

In [ ]:
b

In [ ]:
a > b

In [ ]:
a[a > b]

## Summarizing operations

In [ ]:
a

In [ ]:
a.std()

In [ ]:
n.min()

### Next

Linear algebra refresher